[package]
name = "av-format"
description = "Multimedia format demuxing and muxing"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]

[dependencies]
error-chain = "0.11.0"
bitflags = "0.5.0"

[dependencies.av-data]
path = "../data"
version = "*"
