[package]
name = "av"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
homepage = "https://github.com/rust-av/rust-av"
keywords = ["multimedia"]
license = "LGPL-2.1"

[features]
nightly = []

[dependencies]
bitflags = "0.5.0"
interpolate_idents = "0.1.7"
error-chain = "0.10.0"

[dependencies.av-data]
path = "data"
version = "*"

[dependencies.av-format]
path = "format"
version = "*"

[workspace]
members = [
    "codec",
    "data",
    "format",
]

[dev-dependencies]
assert_matches = "1.1"
