[package]
name = "av-bitstream"
description = "Simple bit writer/reader"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
license = "MIT"
repository = "https://github.com/rust-av/rust-av"

[dependencies]
failure = "0.1"

[dev-dependencies]
assert_matches = "1.1"
