[package]
name = "av-codec"
description = "Multimedia format decoding and encoding"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]

[dependencies]
num-rational = "0.1"
error-chain = "0.6.0"
bitflags = "0.5.0"

[dependencies.av-data]
path = "../data"
version = "*"
